# Run a short performance test against the paladin quick start running in kind
# Note that this is for demonstration purposes only. The quick start system is
# not optimised for performance.
nodes:
  - name: node1
    httpEndpoint: http://127.0.0.1:31548
    wsEndpoint: ws://127.0.0.1:31549
instances:
  - name: test
    test:
      name: public_contract
      workers: 30
      actionsPerLoop: 10
    maxTimePerAction: 60s
    delinquentAction: log
    length: 1m
    rampLength: 30s
logLevel: debug    
