nodeName: node3
db:
  type: sqlite
  sqlite:
    dsn: ":memory:"
    autoMigrate: true
    migrationsDir: "../../db/migrations/sqlite"
    debugQueries: false
grpc:
  shutdownTimeout: 0s
rpcServer:
  http:
    port: 0
    shutdownTimeout: 0s
  ws:
    disabled: true
    shutdownTimeout: 0s
blockIndexer:
  fromBlock: latest
blockchain:
  http:
    url: http://localhost:8545
  ws:
    url: ws://localhost:8546
    initialConnectAttempts: 25
wallets:
  - name: wallet1
    keySelector: .*
    signer:
      keyDerivation:
        type: "bip32"
      keyStore:
        type: "static"
        static:
          keys:
            seed:
              encoding: none
              inline: c461057bef2aeaf43816f95b3c41b667d6fa56342f278d9237d7463226fd101f
